# This is a basic workflow to help you get started with Actions

name: Bitbake dunfell

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  bitbake-dunfell-raspberrypi4-64:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Install essential host packages
      - name: Install Pakages
        run: |
          sudo apt-get -y install gawk wget git-core diffstat unzip texinfo gcc-multilib build-essential chrpath socat cpio python3 python3-pip python3-pexpect xz-utils debianutils iputils-ping python3-git python3-jinja2 libegl1-mesa libsdl1.2-dev pylint3 xterm
          sudo apt-get clean
      
      # Check space before cleanup
      - name: Check space before cleanup
        run: |
          df -h
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          df -h
          
      # checkout repository
      - name: Clone poky, meta-raspberrypi, meta-openembedded
        run: |
          git clone -b dunfell git://git.yoctoproject.org/poky.git
          git clone -b dunfell git://git.yoctoproject.org/meta-raspberrypi
          git clone -b dunfell git://git.openembedded.org/meta-openembedded
        working-directory: ../

      # Run bitbake
      - name: Bitbake MACHINE=raspberrypi4-64, TensorFlow-Lite v2.7.0
        run: |
          source poky/oe-init-build-env rpi-build
          bitbake-layers add-layer ../meta-openembedded/meta-oe/
          bitbake-layers add-layer ../meta-openembedded/meta-python/
          bitbake-layers add-layer ../meta-openembedded/meta-networking/
          bitbake-layers add-layer ../meta-openembedded/meta-multimedia/
          bitbake-layers add-layer ../meta-raspberrypi/
          bitbake-layers add-layer ../meta-tensorflow-lite/
          cat <<EOF> conf/auto.conf
          PREFERRED_VERSION_python3-tensorflow-lite="2.7.0"
          EOF
          cat conf/auto.conf
          MACHINE=raspberrypi4-64 bitbake python3-tensorflow-lite
        working-directory: ../
        
      - name: Bitbake MACHINE=raspberrypi4-64, TensorFlow-Lite v2.6.2
        run: |
          source poky/oe-init-build-env rpi-build
          rm -rf conf/auto.conf
          cat <<EOF> conf/auto.conf
          PREFERRED_VERSION_python3-tensorflow-lite="2.6.2"
          EOF
          cat conf/auto.conf
          MACHINE=raspberrypi4-64 bitbake python3-tensorflow-lite
        working-directory: ../
          
      - name: Bitbake MACHINE=raspberrypi4-64, TensorFlow-Lite v2.5.2
        run: |
          source poky/oe-init-build-env rpi-build
          rm -rf conf/auto.conf
          cat <<EOF> conf/auto.conf
          PREFERRED_VERSION_python3-tensorflow-lite="2.5.2"
          EOF
          cat conf/auto.conf
          MACHINE=raspberrypi4-64 bitbake python3-tensorflow-lite
        working-directory: ../
          
      - name: Bitbake MACHINE=raspberrypi4-64, TensorFlow-Lite v2.4.4
        run: |
          source poky/oe-init-build-env rpi-build
          rm -rf conf/auto.conf
          cat <<EOF> conf/auto.conf
          PREFERRED_VERSION_python3-tensorflow-lite="2.4.4"
          EOF
          cat conf/auto.conf
          MACHINE=raspberrypi4-64 bitbake python3-tensorflow-lite
        working-directory: ../

      - name: Bitbake MACHINE=raspberrypi4-64, TensorFlow-Lite v2.3.4
        run: |
          source poky/oe-init-build-env rpi-build
          rm -rf conf/auto.conf
          cat <<EOF> conf/auto.conf
          PREFERRED_VERSION_python3-tensorflow-lite="2.3.4"
          EOF
          cat conf/auto.conf
          MACHINE=raspberrypi4-64 bitbake python3-tensorflow-lite
        working-directory: ../
        
  bitbake-dunfell-raspberrypi4:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Install essential host packages
      - name: Install Pakages
        run: |
          sudo apt-get -y install gawk wget git-core diffstat unzip texinfo gcc-multilib build-essential chrpath socat cpio python3 python3-pip python3-pexpect xz-utils debianutils iputils-ping python3-git python3-jinja2 libegl1-mesa libsdl1.2-dev pylint3 xterm
          sudo apt-get clean
      
      # Check space before cleanup
      - name: Check space before cleanup
        run: |
          df -h
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          df -h
          
      # checkout repository
      - name: Clone poky, meta-raspberrypi, meta-openembedded
        run: |
          git clone -b dunfell git://git.yoctoproject.org/poky.git
          git clone -b dunfell git://git.yoctoproject.org/meta-raspberrypi
          git clone -b dunfell git://git.openembedded.org/meta-openembedded
        working-directory: ../

      # Run bitbake
      - name: Bitbake MACHINE=raspberrypi4, TensorFlow-Lite v2.7.0
        run: |
          source poky/oe-init-build-env rpi-build
          bitbake-layers add-layer ../meta-openembedded/meta-oe/
          bitbake-layers add-layer ../meta-openembedded/meta-python/
          bitbake-layers add-layer ../meta-openembedded/meta-networking/
          bitbake-layers add-layer ../meta-openembedded/meta-multimedia/
          bitbake-layers add-layer ../meta-raspberrypi/
          bitbake-layers add-layer ../meta-tensorflow-lite/
          cat <<EOF> conf/auto.conf
          PREFERRED_VERSION_python3-tensorflow-lite="2.7.0"
          EOF
          cat conf/auto.conf
          MACHINE=raspberrypi4 bitbake python3-tensorflow-lite
        working-directory: ../

      - name: Bitbake MACHINE=raspberrypi4, TensorFlow-Lite v2.6.2
        run: |
          source poky/oe-init-build-env rpi-build
          rm -rf conf/auto.conf
          cat <<EOF> conf/auto.conf
          PREFERRED_VERSION_python3-tensorflow-lite="2.6.2"
          EOF
          cat conf/auto.conf
          MACHINE=raspberrypi4 bitbake python3-tensorflow-lite
        working-directory: ../
          
      - name: Bitbake MACHINE=raspberrypi4, TensorFlow-Lite v2.5.2
        run: |
          source poky/oe-init-build-env rpi-build
          rm -rf conf/auto.conf
          cat <<EOF> conf/auto.conf
          PREFERRED_VERSION_python3-tensorflow-lite="2.5.2"
          EOF
          cat conf/auto.conf
          MACHINE=raspberrypi4 bitbake python3-tensorflow-lite
        working-directory: ../
          
      - name: Bitbake MACHINE=raspberrypi4, TensorFlow-Lite v2.4.4
        run: |
          source poky/oe-init-build-env rpi-build
          rm -rf conf/auto.conf
          cat <<EOF> conf/auto.conf
          PREFERRED_VERSION_python3-tensorflow-lite="2.4.4"
          EOF
          cat conf/auto.conf
          MACHINE=raspberrypi4 bitbake python3-tensorflow-lite
        working-directory: ../

      - name: Bitbake MACHINE=raspberrypi4, TensorFlow-Lite v2.3.4
        run: |
          source poky/oe-init-build-env rpi-build
          rm -rf conf/auto.conf
          cat <<EOF> conf/auto.conf
          PREFERRED_VERSION_python3-tensorflow-lite="2.3.4"
          EOF
          cat conf/auto.conf
          MACHINE=raspberrypi4 bitbake python3-tensorflow-lite
        working-directory: ../
